"""Writes the Mermaid diagram of the compiled chat graph into docs/ARCHITECTURE.md
(spec 1.2 criterion 3), so the documentation cannot drift from the code.

The graph is compiled with placeholder services: building it opens no
connections, and the diagram depends only on nodes and edges."""

from pathlib import Path
from typing import Any

from langchain_core.language_models.fake_chat_models import GenericFakeChatModel
from langchain_core.messages import AIMessage

from etheria.graph.builder import build_graph, mermaid
from etheria.graph.deps import GraphDeps
from etheria.safety.cautions import load_cautions
from etheria.safety.triage_rules import RuleMatcher

START = "<!-- chat-graph:start (generated by `uv run etheria graph-diagram`; do not edit) -->"
END = "<!-- chat-graph:end -->"

HEADER = """# Architecture

This file is maintained with the code. The chat-graph diagram below is generated
from the compiled LangGraph `StateGraph` by `uv run etheria graph-diagram`
(spec 1.2 criterion 3); dotted arrows are conditional edges. The design and the
reasons behind it are in `docs/superpowers/specs/2026-09-28-etheria-v2-design.md`.

## Chat graph

"""


class _PlaceholderModels:
    def structured(self, node: str, schema: type) -> Any:
        return GenericFakeChatModel(messages=iter([AIMessage("")]))

    def chat(self, node: str) -> Any:
        return GenericFakeChatModel(messages=iter([AIMessage("")]))


def chat_graph_mermaid() -> str:
    deps = GraphDeps(
        db=None,  # type: ignore[arg-type]
        models=_PlaceholderModels(),
        matcher=RuleMatcher.load(),
        cautions=load_cautions(),
        explorer=None,
        interactions=None,
        resolver=None,
        pubmed=None,
        medlineplus=None,
        query_embedder=None,  # type: ignore[arg-type]
    )
    return mermaid(build_graph(deps)).strip()


def write_diagram(path: Path) -> None:
    block = f"{START}\n\n```mermaid\n{chat_graph_mermaid()}\n```\n\n{END}"
    current = path.read_text(encoding="utf-8") if path.exists() else HEADER + START + "\n" + END
    if START not in current or END not in current:
        current = current.rstrip() + "\n\n" + START + "\n" + END + "\n"
    before, rest = current.split(START, 1)
    _, after = rest.split(END, 1)
    path.write_text(before + block + after, encoding="utf-8")
